spring.application.name=url-shortener

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

app.jwt.secret=apfel-birne-salat-obst-redbull-kohlenstoff-daniele-hottingen
app.jwt.expiration-days=7
app.jwt.cookie-name=auth_token
app.cookie.secure=false
